name: CI/CD

on: [push, workflow_dispatch]

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Download Code
        uses: actions/checkout@v3

      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build Artefacts
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            jonathancsr/my-sample-api:${{ github.run_number }}
            jonathancsr/my-sample-api:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]

    steps:
      - name: Download Code
        uses: actions/checkout@v3

      - name: Okteto Login
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_API_KEY }}

      - name: Okteto Deploy
        uses: okteto/apply@latest
        with:
          manifest: k8s/deployment.yaml

  QA:
    needs: [CD]
    runs-on: ubuntu-latest

    steps:
      - name: Download Code
        uses: actions/checkout@v3

      - name: Sleep for 45s
        uses: juliangruber/sleep-action@v2.0.0
        with:
          time: 45s

      - name: QA tests
        run: chmod +x test/qa.sh; test/qa.sh
